const escape = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ],
  );

/** A deterministic, accessible renderer kept separate from scheduling and publication. */
export function greetingHtml(title, members, options = {}) {
  const subtitle = options.subtitle ?? "八个人，一份共同的感谢";
  const intro = options.intro ?? "谢谢您把耐心、方法与勇气留在我们的成长里。";
  const sectionTitle = options.sectionTitle ?? "八封写给导师的信";
  const highlights = options.highlights ?? [
    { title: "工作上手", text: "从理解目标到掌握方法，在耐心指导中更快找到工作的节奏。" },
    { title: "专业成长", text: "在反馈、复盘与实践中，逐渐建立自己的判断与信心。" },
    { title: "团队融入", text: "理解协作方式，在坦诚沟通中成为彼此可靠的伙伴。" },
    { title: "生活关怀", text: "忙碌之外的问候与陪伴，让新的环境始终保有温度。" },
  ];
  const journey = options.journey ?? [
    { title: "初见", text: "带着期待走进小艺，也带着许多未知开始新的旅程。" },
    { title: "上手", text: "在导师的讲解与示范中，把陌生任务拆成清晰的下一步。" },
    { title: "成长", text: "从一次次反馈中积累方法，也在独立思考中建立信心。" },
    { title: "同行", text: "把得到的耐心传递下去，在团队中成为更可靠的伙伴。" },
  ];
  const closingTitle = options.closingTitle ?? "新程有您，步履更坚定";
  const closing =
    options.closing ??
    "感谢您以经验为灯，也以关怀为伴。未来我们会带着这份耐心与认真继续成长。";
  const theme = options.theme ?? "paper-garden";
  const layout = options.layout ?? "gallery";
  const motion = options.motion ?? "gentle";
  const musicPath = options.musicPath;
  const videoPath = options.videoPath;
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="${escape(subtitle)}"><title>${escape(title)}</title>
<style>
:root{color-scheme:light;--paper:#f7f3e9;--surface:#fffdf8;--ink:#19372f;--muted:#68776f;--line:#dce4d8;--accent:#527a65;--accent-soft:#dce9de;--warm:#e8b978;--shadow:0 24px 70px rgba(49,70,58,.12)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.8 ui-serif,"Songti SC","Noto Serif SC",serif;overflow-x:hidden}
body[data-theme="warm-gallery"]{--paper:#fbf2e8;--surface:#fffaf5;--ink:#4b3027;--muted:#80675d;--line:#ead8c8;--accent:#a4624c;--accent-soft:#f3dfd1;--warm:#d9925f}
body[data-theme="night-sky"]{--paper:#101d2b;--surface:#17283a;--ink:#f7f0df;--muted:#b8c4ca;--line:#31485c;--accent:#8bc7c0;--accent-soft:#223f4c;--warm:#e5bd72;--shadow:0 24px 70px rgba(0,0,0,.3)}
.grain{position:fixed;inset:0;pointer-events:none;opacity:.16;background-image:radial-gradient(#6f806f 0.55px,transparent .6px);background-size:7px 7px;mix-blend-mode:multiply}.orb{position:absolute;border-radius:50%;filter:blur(1px);opacity:.58;pointer-events:none}.orb-a{width:24rem;height:24rem;right:-9rem;top:-8rem;background:radial-gradient(circle,#f1c88e66,transparent 68%)}.orb-b{width:20rem;height:20rem;left:-9rem;top:22rem;background:radial-gradient(circle,#9bc9ab55,transparent 70%)}
main{position:relative;max-width:1180px;margin:auto;padding:clamp(28px,6vw,76px) clamp(18px,4vw,44px) 46px}.site-nav{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:4px 0 20px;border-bottom:1px solid var(--line);font:600 12px/1.4 ui-sans-serif,system-ui,sans-serif}.site-nav strong{letter-spacing:.16em}.site-nav div{display:flex;align-items:center;gap:18px}.site-nav a{color:var(--muted);text-decoration:none}.site-nav a:hover{color:var(--accent)}.music-toggle{display:inline-flex;align-items:center;gap:7px;padding:7px 11px;border:1px solid var(--line);border-radius:999px;background:var(--surface);color:var(--accent);font:inherit;cursor:pointer}.music-toggle:before{content:"♪";font-size:15px}.music-toggle[data-playing="true"]:before{animation:pulse 1.2s ease-in-out infinite}.hero{min-height:64vh;display:grid;align-content:center;justify-items:center;text-align:center;padding:58px 0 72px}.eyebrow{display:inline-flex;align-items:center;gap:9px;margin:0 0 20px;padding:7px 13px;border:1px solid var(--line);border-radius:999px;background:color-mix(in srgb,var(--surface) 82%,transparent);color:var(--accent);font:700 12px/1.2 ui-sans-serif,system-ui,sans-serif;letter-spacing:.16em}.eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--warm);box-shadow:0 0 0 5px color-mix(in srgb,var(--warm) 20%,transparent)}h1{max-width:none;margin:0;white-space:nowrap;font-size:clamp(44px,6vw,78px);font-weight:500;line-height:1.08;letter-spacing:.015em}.subtitle{max-width:900px;margin:24px 0 0;color:var(--accent);font-size:clamp(18px,2.2vw,27px);line-height:1.65;letter-spacing:.04em}.intro{max-width:760px;margin:24px auto 0;color:var(--muted);font-size:clamp(15px,1.6vw,18px)}.hero-meta{display:flex;gap:10px;margin-top:30px;flex-wrap:wrap;justify-content:center}.hero-meta span{padding:6px 12px;border-radius:999px;background:var(--accent-soft);color:var(--accent);font:600 12px/1.4 ui-sans-serif,system-ui,sans-serif}
.chapter{margin:0 0 76px}.highlights{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.highlight{min-height:190px;padding:24px;border:1px solid var(--line);border-radius:22px;background:var(--surface);box-shadow:0 8px 28px rgba(53,70,60,.05)}.highlight span{display:block;color:var(--warm);font:700 12px/1 ui-sans-serif,system-ui,sans-serif;letter-spacing:.14em}.highlight h3{margin:30px 0 8px;font-size:22px}.highlight p{margin:0;color:var(--muted);font-size:14px}.journey{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;padding:28px;border:1px solid var(--line);border-radius:28px;background:color-mix(in srgb,var(--surface) 88%,transparent)}.journey-step{position:relative;padding:12px 24px;border-left:1px solid var(--line)}.journey-step:first-child{border-left:0}.journey-step:before{content:"";position:absolute;left:-5px;top:19px;width:9px;height:9px;border-radius:50%;background:var(--warm)}.journey-step:first-child:before{display:none}.journey-step b{font-size:18px}.journey-step p{margin:8px 0 0;color:var(--muted);font-size:13px}
.section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin:0 0 26px}.section-head p{margin:0;color:var(--muted);font:500 12px/1.5 ui-sans-serif,system-ui,sans-serif;letter-spacing:.12em;text-transform:uppercase}.section-head h2{margin:4px 0 0;font-size:clamp(28px,4vw,44px);font-weight:500}.section-count{font-size:70px;line-height:.8;color:color-mix(in srgb,var(--accent) 18%,transparent);font-style:italic}
.media-stage{position:relative;overflow:hidden;padding:clamp(16px,3vw,28px);border:1px solid var(--line);border-radius:30px;background:var(--surface);box-shadow:var(--shadow)}.media-stage:before{content:"";position:absolute;inset:auto -8% -45% auto;width:50%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,var(--accent-soft),transparent 70%);pointer-events:none}.media-stage video{position:relative;display:block;width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:20px;background:#15251f}.media-caption{position:relative;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:18px 4px 0}.media-caption h3{margin:0;font-size:22px}.media-caption p{max-width:620px;margin:0;color:var(--muted);font-size:14px}
.people{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.people[data-layout="timeline"]{grid-template-columns:repeat(2,minmax(0,1fr));position:relative}.people[data-layout="timeline"]:before{content:"";position:absolute;top:0;bottom:0;left:50%;width:1px;background:var(--line)}article{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:24px;background:color-mix(in srgb,var(--surface) 94%,transparent);box-shadow:0 8px 30px rgba(53,70,60,.06);transition:transform .3s ease,box-shadow .3s ease,border-color .3s ease;animation:card-in .65s both}article:nth-child(2){animation-delay:70ms}article:nth-child(3){animation-delay:140ms}article:nth-child(4){animation-delay:210ms}article:nth-child(5){animation-delay:280ms}article:nth-child(6){animation-delay:350ms}article:nth-child(7){animation-delay:420ms}article:nth-child(8){animation-delay:490ms}article:hover{transform:translateY(-6px);border-color:color-mix(in srgb,var(--accent) 45%,var(--line));box-shadow:var(--shadow)}.portrait{position:relative;margin:10px;overflow:hidden;border-radius:18px;background:var(--accent-soft);aspect-ratio:1}.portrait:after{content:"";position:absolute;inset:0;border:1px solid rgba(255,255,255,.45);border-radius:inherit;pointer-events:none}.portrait img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .7s cubic-bezier(.2,.75,.25,1)}article:hover img{transform:scale(1.035)}.card-body{padding:10px 20px 22px}.member-line{display:flex;align-items:center;justify-content:space-between;gap:10px}.member-line h3{margin:0;font-size:21px;font-weight:600}.keyword{padding:3px 9px;border-radius:999px;background:var(--accent-soft);color:var(--accent);font:700 10px/1.5 ui-sans-serif,system-ui,sans-serif;letter-spacing:.08em}.blessing{margin-top:12px}.blessing summary{cursor:pointer;list-style:none;color:var(--muted);font:600 11px/1.5 ui-sans-serif,system-ui,sans-serif;letter-spacing:.08em}.blessing summary::-webkit-details-marker{display:none}.blessing summary:after{content:"＋";float:right;color:var(--accent)}.blessing[open] summary:after{content:"－"}.blessing p{margin:10px 0 0;font-size:15px;line-height:1.85;white-space:pre-wrap}
.closing{display:grid;grid-template-columns:1fr auto;align-items:center;gap:30px;margin-top:76px;padding:42px clamp(24px,5vw,56px);border:1px solid var(--line);border-radius:28px;background:var(--surface);box-shadow:0 14px 44px rgba(50,70,58,.07)}.closing h2{margin:0 0 8px;font-size:clamp(28px,4vw,44px);font-weight:500}.closing p{margin:0;color:var(--muted)}.seal{display:grid;place-items:center;width:92px;height:92px;border:1px solid var(--warm);border-radius:50%;color:var(--accent);font-size:13px;letter-spacing:.14em;transform:rotate(-7deg)}footer{text-align:center;color:var(--muted);margin-top:44px;font:500 11px/1.8 ui-sans-serif,system-ui,sans-serif;letter-spacing:.12em}
@keyframes card-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}@keyframes pulse{50%{transform:scale(1.25);opacity:.62}}@media(max-width:900px){h1{font-size:clamp(40px,7vw,62px)}.people,.highlights{grid-template-columns:repeat(2,minmax(0,1fr))}.journey{grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.journey-step:nth-child(3){border-left:0}}@media(max-width:640px){h1{white-space:normal;text-wrap:balance}.site-nav div a{display:none}.hero{min-height:auto;padding-top:54px}.people,.people[data-layout="timeline"],.highlights,.journey{grid-template-columns:1fr}.people[data-layout="timeline"]:before{display:none}.journey-step,.journey-step:nth-child(3){border-left:0;border-top:1px solid var(--line)}.journey-step:first-child{border-top:0}.journey-step:before{display:none}.section-count{font-size:48px}.closing{grid-template-columns:1fr}.seal{width:76px;height:76px}.media-caption{display:block}.media-caption p{margin-top:8px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{animation:none!important;transition:none!important}}body[data-motion="reduced"] *,body[data-motion="reduced"] *:before,body[data-motion="reduced"] *:after{animation:none!important;transition:none!important}
</style></head>
<body data-theme="${escape(theme)}" data-motion="${escape(motion)}"><div class="grain"></div><div class="orb orb-a"></div><div class="orb orb-b"></div>
<main><nav class="site-nav" aria-label="页面导航"><strong>小艺新程</strong><div><a href="#growth">成长收获</a><a href="#journey">成长路径</a>${videoPath ? '<a href="#film">感谢短片</a>' : ""}<a href="#letters">写给导师</a>${musicPath ? '<button class="music-toggle" id="music-toggle" type="button" aria-pressed="false" data-playing="false">播放音乐</button>' : ""}</div></nav>${musicPath ? `<audio id="background-music" src="${escape(musicPath)}" preload="metadata" loop></audio>` : ""}<header class="hero"><p class="eyebrow">XIAOYI NEW JOURNEY · WITH GRATITUDE</p><h1>${escape(title)}</h1><p class="subtitle">${escape(subtitle)}</p><p class="intro">${escape(intro)}</p><div class="hero-meta"><span>${members.length} 位新人</span><span>${members.length} 份感谢</span><span>共同成长</span></div></header>
<section class="chapter" id="growth" aria-labelledby="growth-title"><div class="section-head"><div><p>What we gained</p><h2 id="growth-title">成长的四个切面</h2></div><span class="section-count">04</span></div><div class="highlights">${highlights.map((item, index) => `<div class="highlight"><span>0${index + 1}</span><h3>${escape(item.title)}</h3><p>${escape(item.text)}</p></div>`).join("")}</div></section>
<section class="chapter" id="journey" aria-labelledby="journey-title"><div class="section-head"><div><p>Our journey</p><h2 id="journey-title">从新人，到并肩同行</h2></div></div><div class="journey">${journey.map((item) => `<div class="journey-step"><b>${escape(item.title)}</b><p>${escape(item.text)}</p></div>`).join("")}</div></section>
${videoPath ? `<section class="chapter" id="film" aria-labelledby="film-title"><div class="section-head"><div><p>A moment of gratitude</p><h2 id="film-title">把感谢，写进一段光影</h2></div><span class="section-count">10″</span></div><div class="media-stage"><video id="thanks-video" src="${escape(videoPath)}" controls preload="metadata" playsinline aria-describedby="film-description"></video><div class="media-caption"><h3>小艺新程 · 感谢有您</h3><p id="film-description">一段由 AI 生成的原创感谢短片，以纸艺花园和温暖光线记录陪伴、引导与成长。</p></div></div></section>` : ""}
<section id="letters" aria-labelledby="wishes-title"><div class="section-head"><div><p>Letters to mentors</p><h2 id="wishes-title">${escape(sectionTitle)}</h2></div><span class="section-count">${String(members.length).padStart(2, "0")}</span></div>
<div class="people" data-layout="${escape(layout)}">${members
    .map(
      (member, index) =>
        `<article><div class="portrait"><img src="${escape(member.imagePath)}" alt="${escape(member.name)}的原创纸艺虚构头像" loading="${index > 3 ? "lazy" : "eager"}"></div><div class="card-body"><div class="member-line"><h3>${escape(member.name)}</h3><span class="keyword">${escape(member.keyword ?? "感谢")}</span></div><details class="blessing" open><summary>写给导师的话</summary><p>${escape(member.blessing)}</p></details></div></article>`,
    )
    .join("")}</div></section>
<section class="closing"><div><p class="eyebrow">WITH GRATITUDE</p><h2>${escape(closingTitle)}</h2><p>${escape(closing)}</p></div><div class="seal" aria-label="教师节感谢">师恩<br>相伴</div></section>
<footer>由「艺工作」多 Agent 协作生成 · AI 多干活，我们少干活，让工作更简单</footer></main>${musicPath ? `<script>(()=>{const audio=document.getElementById("background-music"),button=document.getElementById("music-toggle"),video=document.getElementById("thanks-video");let resumeAfterVideo=false;const sync=()=>{const playing=!audio.paused;button.dataset.playing=String(playing);button.setAttribute("aria-pressed",String(playing));button.textContent=playing?"暂停音乐":"播放音乐"};button.addEventListener("click",async()=>{if(audio.paused){try{await audio.play()}catch{} }else audio.pause();sync()});audio.addEventListener("play",sync);audio.addEventListener("pause",sync);if(video){video.addEventListener("play",()=>{resumeAfterVideo=!audio.paused;if(resumeAfterVideo)audio.pause()});video.addEventListener("ended",async()=>{if(resumeAfterVideo){try{await audio.play()}catch{} resumeAfterVideo=false}});video.addEventListener("pause",()=>{if(video.ended)return;if(resumeAfterVideo){audio.play().catch(()=>{});resumeAfterVideo=false}})}})();</script>` : ""}</body></html>`;
}
